### ISSUE TITLE
Feature Request - Add depth argument

### ISSUE THREAD

**Issue by kerbs17** [adiktofsugar/diff-package-lock#38]
I would like to be able to see just the top-level version changes easily, it would be nice to have a --depth argument I can pass similar to npm's [ls command](https://docs.npmjs.com/cli/v7/commands/npm-ls#depth)

Ex: `npx diff-package-lock --depth=0 .` to list only the top level version changes

**Comment by adiktofsugar** [comment]
Man, wrapping my brain around how 0 meant number of recursions took longer than making the actual change, haha. It's now in 0.1.33!
